language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - addon-google_gdk-google-19
  licenses:
    - '.+'

script:
  - ./gradlew clean assembleDebug -s -i

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
