language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-23.0.0
    - android-23
    - addon-google_gdk-google-19
  licenses:
    - '.+'

script:
 - ./gradlew clean assembleDebug -Dpre-dex=false --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
